djangocrud/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('respuestas/', views.respuestas, name='respuestas'),
    path('list_tasks/', views.list_tasks, name='list_tasks'),
    path('list_usuarios/', views.list_usuarios, name='list_usuarios'),
    path('list_solicitudes/', views.list_solicitudes, name='list_solicitudes'),

    path('dashboard_admin/', views.dashboard_admin, name='dashboard_admin'),
    path('dashboard_ejecutivo/', views.dashboard_ejecutivo, name='dashboard_ejecutivo'),
    path('dashboard_cliente/', views.dashboard_cliente, name='dashboard_cliente'),
    path('solicitudes/', views.solicitudes, name='solicitudes'),

    path('tasks/create/', views.create_task, name='create_task'),
    path('obtener_subcategorias/', views.obtener_subcategorias, name='obtener_subcategorias'),
    path('solicitudes/create/', views.create_solicitud, name='create_solicitud'),

    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('solicitudes_completed/', views.solicitudes_completed, name='solicitudes_completed'),

    path('tasks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('solicitudes/<int:solicitud_id>/complete', views.complete_solicitud, name='complete_solicitud'),

    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('solicitudes/<int:solicitud_id>/', views.solicitud_detail, name='solicitud_detail'),


    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('solicitudes/<int:solicitud_id>/delete', views.delete_solicitud, name='delete_solicitud'),

    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),

    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User

task_complejidad=[
    (1, 'Baja'),
    (2, 'Media'),
    (3, 'Alta')
]

solicitud_estado=[
    (1, 'Pendiente'),
    (2, 'En proceso'),
    (3, 'En espera del cliente'),
    (4, 'Resuelto')
]
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, first_name, last_name, mobile, **extra_fields):
        if not email:
            raise ValueError("Email must be provided")
        if not password:
            raise ValueError("Password is not provided")

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            mobile=mobile,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, first_name, last_name, mobile,**extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_admin', False)
        extra_fields.setdefault('is_ejecutivo', False)
        extra_fields.setdefault('is_cliente', False)
        return self._create_user(email, password, first_name, last_name, mobile ,**extra_fields)

    def create_superuser(self, email, password, first_name, last_name, mobile , **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_admin', False)
        extra_fields.setdefault('is_ejecutivo', False)
        extra_fields.setdefault('is_cliente', False)
        return self._create_user(email, password, first_name, last_name, mobile, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(db_index=True, unique=True, max_length=254)
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=255)
    mobile = models.CharField(max_length=50, null=True)
    adress = models.CharField(max_length=250, null=True)

    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_ejecutivo = models.BooleanField(default=False)
    is_cliente = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

class Categoria(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    code = models.CharField(max_length=48)
    def __str__(self):
        return self.title

class Subcategoria(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=48)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Task(models.Model):
    nombre = models.CharField(max_length=100)
    complejidad = models.IntegerField(
        null=False, blank=False,
        choices=task_complejidad
    )
    created = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=48, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.CASCADE,null=False, blank=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Respuesta(models.Model):
    code = models.CharField(max_length=48, null=True)
    description = models.CharField(null=False, max_length=255)
    comentario = models.CharField(blank=True, null=True, max_length=100)
    requerimiento = models.ForeignKey(Task, blank=True, null=True, on_delete=models.CASCADE)
    formulario = models.URLField(blank=True, null=True)
    def __str__(self):
        return self.requerimiento.nombre

class Solicitud(models.Model):
    comentario = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    estado = models.IntegerField(
        null=False, blank=False,
        choices=solicitud_estado, default=solicitud_estado[0][0]
    )
    datecompleted = models.DateTimeField(null=True, blank=True)
    requerimiento = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.comentario

tasks/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.views.decorators.http import require_GET

from .forms import TaskForm, SolicitudForm, SignUpForm, LoginForm
from .models import Task, Solicitud, Categoria, Subcategoria, Respuesta
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()
#Vistas

#Inicio
def home(request):
    return render(request, 'home.html')
#Registro
def signup(request):
    msg = None
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            msg = 'user created'
            return redirect('dashboard_admin')
        else:
            msg = 'form is not valid'
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form, 'msg': msg})

#Requerimientos
@login_required
def tasks(request):
    tasks = Task.objects.filter(user=request.user)
    return render(request, 'tasks.html', {'tasks' : tasks})

#Respuestas
@login_required
def respuestas(request):
    respuestas = Respuesta.objects.filter()
    return render(request, 'respuestas.html', {'respuestas' : respuestas})

#Dashboard Admin
def dashboard_admin(request):
    tasks = Task.objects.filter()
    categorias = Categoria.objects.filter()
    subcategorias = Subcategoria.objects.filter()
    solicitudes = Solicitud.objects.filter()
    users = User.objects.filter()
    return render(request, 'dashboard_admin.html', {'tasks' : tasks,
                                                    'categorias': categorias,
                                                    'subcategorias': subcategorias,
                                                    'solicitudes': solicitudes,
                                                    'users': users
                                                    })

#Dashboard ejecutivo
def dashboard_ejecutivo(request):
    tasks = Task.objects.filter()
    categorias = Categoria.objects.filter()
    subcategorias = Subcategoria.objects.filter()
    solicitudes = Solicitud.objects.filter()
    users = User.objects.filter()
    return render(request, 'dashboard_ejecutivo.html', {'tasks' : tasks,
                                                    'categorias': categorias,
                                                    'subcategorias': subcategorias,
                                                    'solicitudes': solicitudes,
                                                    'users': users
                                                    })

#Lista de Requerimientos devuelve un JSON para insertar datos en tablas mediante JavasCript
def list_tasks(_request):
    tasks = Task.objects.values('id', 'nombre', 'categoria_id', 'subcategoria_id')
    task_list = []
    for task in tasks:
        categoria = Categoria.objects.get(id=task['categoria_id'])
        subcategoria = Subcategoria.objects.get(id=task['subcategoria_id'])
        task_dict = {
            'id': task['id'],
            'nombre': task['nombre'],
            'categoria': categoria.title,
            'subcategoria': subcategoria.title,
        }
        task_list.append(task_dict)

    data = {'tasks' : task_list}
    return JsonResponse(data)

#Lista de Usuarios devuelve un JSON para insertar datos en tablas mediante JavasCript
def list_solicitudes(_request):
    solicitudes = Solicitud.objects.values('id', 'comentario', 'user_id', 'requerimiento_id')
    solicitud_list = []
    for solicitud in solicitudes:
        user = User.objects.get(id=solicitud['user_id'])
        task = Task.objects.get(id=solicitud['requerimiento_id'])
        solicitud_dict = {
            'id': solicitud['id'],
            'comentario': solicitud['comentario'],
            'user': user.first_name,
            'requerimiento': task.nombre,
        }
        solicitud_list.append(solicitud_dict)

    data = {'solicitudes' : solicitud_list}
    return JsonResponse(data)



#Lista de Usuarios devuelve un JSON para insertar datos en tablas mediante JavasCript
def list_usuarios(_request):
    users = list(User.objects.values())
    data = {'users' : users}
    return JsonResponse(data)

#dashboard cliente
def dashboard_cliente(request):
    tasks = Task.objects.filter()
    categorias = Categoria.objects.filter()
    subcategorias = Subcategoria.objects.filter()
    solicitudes = Solicitud.objects.filter(user=request.user)
    users = User.objects.filter()
    return render(request, 'dashboard_cliente.html', {'tasks' : tasks,
                                                    'categorias': categorias,
                                                    'subcategorias': subcategorias,
                                                    'solicitudes': solicitudes,
                                                    'users': users
                                                    })


#solicitudes
@login_required
def solicitudes(request):
    solicitudes = Solicitud.objects.filter(user=request.user)
    return render(request, 'solicitudes.html', {'solicitudes' : solicitudes})

#requerimientos completados
@login_required
def tasks_completed(request):
    tasks = Task.objects.filter(user=request.user).order_by('-datecompleted')
    return render(request, 'tasks.html', {'tasks' : tasks})

#solicitudes completadas 
@login_required
def solicitudes_completed(request):
    solicitudes = Solicitud.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'solicitudes.html', {'solicitudes' : solicitudes})

#requerimiento detalle
@login_required
def task_detail(request, task_id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=task_id, user=request.user)
        respuesta = task.respuesta_set.first()
        form = TaskForm(instance=task)
        return render(request, 'task_detail.html', {'task': task, 'respuesta': respuesta, 'form': form})
    else:
        try:
            task = get_object_or_404(Task, pk=task_id, user=request.user)
            respuesta = Respuesta.objects.filter()
            form = TaskForm(request.POST, instance=task)

            form.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'task_detail.html', {'task': task, 'respuesta': respuesta, 'form': form, 'error': "Error updating task"})

#solicitud detalle
@login_required
def solicitud_detail(request, solicitud_id):
    if request.method == 'GET':
        solicitud = get_object_or_404(Solicitud, pk=solicitud_id, user=request.user)
        form = SolicitudForm(instance=solicitud)
        return render(request, 'solicitud_detail.html', {'solicitud': solicitud, 'form': form})
    else:
        try:
            solicitud = get_object_or_404(Solicitud, pk=solicitud_id, user=request.user)
            form = SolicitudForm(request.POST, instance=solicitud)
            form.save()
            return redirect('solicitudes')
        except ValueError:
            return render(request, 'solicitud_detail.html', {'solicitud': solicitud, 'form': form, 'error': "Error updating task"})
        
#requerimiento completado
@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task,pk=task_id, user=request.user)
    if request.method == 'POST':
        task.datecompleted = timezone.now()
        task.save()
        return redirect('dashboard_admin')

#Solicitiud completado
@login_required
def complete_solicitud(request, solicitud_id):
    solicitud = get_object_or_404(Solicitud,pk=solicitud_id, user=request.user)
    if request.method == 'POST':
        solicitud.datecompleted = timezone.now()
        solicitud.save()
        return redirect('dashboard_admin')
#borrar requerimiento

@login_required
def delete_task(request,task_id):
    task = get_object_or_404(Task,pk=task_id, user=request.user)
    if request.method == 'POST':
        task.delete()
        return redirect('dashboard_admin')


@login_required
def delete_solicitud(request,solicitud_id):
    solicitud = get_object_or_404(Solicitud,pk=solicitud_id, user=request.user)
    if request.method == 'POST':
        solicitud.delete()
        return redirect('dashboard_admin')

@login_required
def create_task(request):
    if request.method =='GET':
        return render(request, 'create_task.html', {
            'form': TaskForm
        })
    else:
        try:
            form = TaskForm(request.POST)
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect('dashboard_admin')
        except ValueError:
            return render(request, 'create_task.html', {
                'form': TaskForm,
                'error' : ' Please provide valide data'
            })

@login_required
def create_solicitud(request):
    if request.method =='GET':
        return render(request, 'create_solicitud.html', {
            'form': SolicitudForm
        })
    else:
        try:
            form = SolicitudForm(request.POST)
            new_solicitud = form.save(commit=False)
            new_solicitud.user = request.user
            new_solicitud.save()
            user = request.user
            if user is not None and user.is_admin:
                login(request, user)
                return redirect('dashboard_admin')
            elif user is not None and user.is_ejecutivo:
                login(request, user)
                return redirect('dashboard_ejecutivo')
            elif user is not None and user.is_cliente:
                login(request, user)
                return redirect('dashboard_cliente')
        except ValueError:

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title href="/dashboard_admin/">ContaSMART</title>
    <!-- Bootstrap 5.2.2 css y js-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <!-- table filter , estilos css, js, bootstap icons -->
    <link type="text/css" href='{% static "css/base.css"%}' rel="stylesheet" />
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- DataTable.js -->
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
    <!-- Custom JS -->
    <!--  <script src="{% static 'js/index.js' %}"></script>-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    />
  </head>

  <body>
    <header></header>

    <nav class="navbar navbar-expand-lg bg-dark navbar-dark" id="barra">
      <div class="container">
        <a class="navbar-brand" href="/">ContaSMART</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          adsdsd
          <ul class="navbar-nav ms-auto">
            <!-- <li class="nav-item">
      <a class="nav-link " href="/">Inicio</a>

    </li> -->
            <div class="dropdown">
              <!-- <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Requerimientos
  </button> -->
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{% url 'tasks' %}"
                    >Requerimientos Pendientes</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'tasks_completed' %}"
                    >Requerimientos Completados</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="/tasks/create/"
                    >Crear Requerimiento</a
                  >
                </li>
              </ul>
            </div>
            <!--
        <li class="nav-item">
      <a class="nav-link " href="{% url 'solicitudes' %}">Solicitudes</a>
    </li>  -->
            <!--
            </li>
        <li class="nav-item">
      <a class="nav-link " href="/solicitudes/create/">Crear Solicitud</a>
    </li> -->

            {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="/logout">Cerrar sesión</a>
            </li>
            {% else %}
            <!--   <li class="nav-item">
      <a class="nav-link " href="/signup">Registrarse</a>
    </li> -->
            <li class="nav-item">
              <a class="nav-link" href="/signin">Iniciar sesión</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %} {% block scripts %} {% endblock %}
  </body>
</html>

tasks/templates/create_solicitud.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<main>
    <section class="card card-body bg-transparent text-light align-items-center mt-5">

                <h1 class="text-center text-light mt-5 display-3">Nueva Solicitud</h1 >

            <form action="/solicitudes/create/" method="POST" class="mt-5 mb-5 shortform">

                {% csrf_token %}
                {{ form | crispy }}

                <button class="btn btn-dark mt-3 ">
                    Crear
                </button>
            </form>

    </section>
</main>
{% endblock %}

tasks/templates/create_task.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}
<main>
  <section class="card card-body bg-transparent align-items-center">
    <h1 class="text-center text-light mt-5 mb-5 display-3">
      Crear Requerimiento
    </h1>
    <form action="/tasks/create/" method="POST" class="text-light shortform">
      {% csrf_token %} {{ form | crispy }}
      <button class="btn btn-dark mt-3">Guardar</button>
    </form>
  </section>
</main>

<script>
  const categoriaSelect = document.querySelector("#id_categoria");
  const subcategoriaSelect = document.querySelector("#id_subcategoria");

  categoriaSelect.addEventListener("change", function () {
    const categoriaSeleccionada = categoriaSelect.value;
    const url =
      categoriaSelect.getAttribute("data-url") +
      "?categoria=" +
      categoriaSeleccionada;
    fetch(url)
      .then((response) => response.json())
      .then((data) => {
        subcategoriaSelect.innerHTML = "";
        data.forEach((subcategoria) => {
          const option = document.createElement("option");
          option.text = subcategoria.nombre;
          option.value = subcategoria.id;
          subcategoriaSelect.appendChild(option);
        });
      });
  });
</script>
{% endblock %}

tasks/templates/dashboard_admin.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<main>
  {% csrf_token %}

  <section class="card card-body bg-transparent" id="miau">
    <div class="card card-body bg-transparent">
      <h1 class="text-center text-light display-3 mb-5 mt-5">
        Panel de administrador
      </h1>
      <h4 class="text-center text-light mb-5">
        ¡Bienvenid@ {{ user.first_name }}!
      </h4>
    </div>

    <!--ORDENANDO TODO DE NUEVO -->
    <div class="row">
      <div class="col-12">
        <div class="row text-center">
          <p id="peruvian">
            <a
              class="btn btn-lg btn-outline-light mt-5"
              href="/solicitudes/create/"
            >
              <i class="bi bi-envelope-plus display-6"></i>
            </a>
            <a class="btn btn-lg btn-outline-light mt-5" href="/signup/">
              <i class="bi bi-person-plus display-6"></i>
            </a>

            <a class="btn btn-lg btn-outline-light mt-5" href="/tasks/create/">
              <i class="bi bi-plus-lg display-6"></i>
            </a>

            <a class="btn btn-lg btn-outline-light mt-5" href="">
              <i class="bi bi-gear display-6"></i>
            </a>
          </p>
        </div>
      </div>
    </div>
        <!--   SOLICITUDES -->

    <div class="row">
      <div class="col">
        <div class="card carddark text-white mb-5 mt-5">
          <h2 class="azul mb-5 mt-5 text-center">Todas Solicitudes</h2>
          <table
            id="datatable_solicitudes"
            class="table table-borderless table-hover table-responsive"
          >
            <thead>
              <tr>
                <th scope="col" class="centered">#</th>
                <th scope="col" class="centered">Comentario</th>
                <th scope="col" class="centered">Usuario </th>
                <th scope="col" class="centered">Requerimiento </th>
              </tr>
            </thead>
            <tbody id="tableBody_solicitudes"></tbody>
          </table>
        </div>
        <!-- TODAS LAS SOLICITUDES -->
<!--
        <div class="card card-body mb-3 mt-5">
          <h2 class="azul mb-5 mt-5 text-center">Todas las solicitudes</h2>

          <div class="table-wrapper-scroll-y my-custom-scrollbar">
            <table
              class="table table-borderless table-hover sm table-responsive align-middle"
            >
              <thead>
                <tr>
                  <th data-field="requerimiento" scope="col" class="azul">
                    Requerimiento
                  </th>
                  <th data-field="comentario" class="azul">Comentario</th>
                  <th scope="col" class="azul">Usuario</th>
                  <th scope="col" class="azul">Estado</th>
                </tr>
              </thead>

              {% for solicitud in solicitudes %}

              <tbody>
                <tr>
                  <td scope="row" class="text-dark">
                    {{solicitud.requerimiento}}
                  </td>
                  <td class="text-dark">{{solicitud.comentario}}</td>
                  <td class="text-dark">{{solicitud.user}}</td>
                  {% if solicitud.estado == 1 %}
                  <td class="text-dark">Pendiente</td>
                  {% endif %} {% if solicitud.estado == 2 %}
                  <td class="text-dark">En proceso</td>
                  {% endif %} {% if solicitud.estado == 3 %}
                  <td class="text-dark">En espera del cliente</td>
                  {% endif %} {% if solicitud.estado == 4 %}
                  <td class="text-dark">Resuelto</td>
                  {% endif %}
                </tr>
              </tbody>
              {% endfor %}
            </table>
          </div>
        </div>
-->
        <!-- FIN SOLICITUDES -->
      </div>

      <div class="col">
        <!-- USUARIOS -->

        <div class="card card-body mb-3 mt-5">
          <h2 class="mb-5 mt-5 azul text-center">Clientes y ejecutivos</h2>
          <table
            id="datatable_usuarios"
            class="table table-borderless table-hover table-responsive"
          >
            <thead>
              <tr>
                <th scope="col" class="azul">#</th>
                <th scope="col" class="azul">Nombre</th>
                <th scope="col" class="azul">Apellido</th>
                <th scope="col" class="azul">Correo</th>

              </tr>
            </thead>

            <tbody id="tableBody_usuarios"></tbody>
          </table>
 <!-- 
          <div class="table-wrapper-scroll-y my-custom-scrollbar">
            <table
              class="table table-borderless table-hover mb-0 table-responsive"
            >
              <thead>
                <tr>
                  <th scope="col" class="azul">Nombre completo</th>
                  <th scope="col" class="azul">Correo electrónico</th>
                  <th scope="col" class="azul">Contacto</th>
                  <th scope="col" class="azul">Rol</th>
                </tr>
              </thead>

              {% for user in users %}

              <tbody>
                <tr>
                  <th scope="row" class="azul">
                    {{user.first_name}} {{user.last_name}}
                  </th>
                  <td class="text-dark">{{user.email}}</td>
                  <td class="text-dark">{{user.mobile}}</td>
                  {% if user.is_admin %}
                  <td class="text-dark">Admin</td>
                  {% endif %} {% if user.is_ejecutivo %}
                  <td class="text-dark">Ejecutivo</td>
                  {% endif %} {% if user.is_cliente %}
                  <td class="text-dark">Cliente</td>
                  {% endif %}
                </tr>
              </tbody>
              {% endfor %}
            </table>
          </div>
        </div>-->
      </div>

        <!-- FIN USUARIOS -->
    </div>

    <!-- REQUERIMIENTOS-->

    <div class="card carddark text-white mb-5 mt-5">
      <h2 class="azul mb-5 mt-5 text-center">Requerimientos</h2>
      <table
        id="datatable_requerimientos"
        class="table table-borderless table-hover table-responsive"
      >
        <thead>
          <tr>
            <th scope="col" class="centered">#</th>
            <th scope="col" class="centered">Requerimiento</th>
            <th scope="col" class="centered">Categoría</th>
            <th scope="col" class="centered">Subcategoria</th>
          </tr>
        </thead>
        <tbody id="tableBody_requerimientos"></tbody>
      </table>
    </div>
      
    
    <!-- FIN REQUERIMIENTOS-->
    <!--FIN ORDENANDO TODO DE NUEVO -->
  </section>
</main>

{% endblock %}
<!-- dashboard_admin.html -->

{% block scripts %}
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}

tasks/templates/home.html
{% extends 'base.html' %}

  {% block content %}

<main >
<section >
  <h1 class="display-1 text-center text-light">ContaSMART </h1>
  <p class="text-center text-light">Contabilidad inteligente</p>
  <div class="text-center">
  <a class="btn btn-dark" href="/signin/">
    Iniciar sesión
  </a> <!--
  <a class="btn btn-dark" href="/signup/">
    Registrarse
  </a> -->
  </div>
  </section>
</main>
{% endblock %}

tasks/templates/solicitud_detail.html
{% extends 'base.html' %}

  {% block content %}
<main>
    <section>
        <div class="col-md-4 offset-md-4">
            <h1>{{solicitud.comentario}}</h1>
                    {{error}}
                <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
<button class="btn btn-dark">
  update
</button>
</form>
<div class="mt-5 d-flex">

<form action= "{% url 'complete_solicitud' solicitud.id %}" method="POST">
    {% csrf_token %}

    <button class="btn btn-secondary">
        Complete
    </button>
</form>


</div>
        </div>
    </section>
</main>
  {% endblock %}